# any-edit
#
# SPDX-FileCopyrightText: 2025-2026 Steve Schoettler
# SPDX-License-Identifier: Apache-2.0
#
[package]
name = "any-edit"
version.workspace = true
authors.workspace = true
categories = ["command-line-utilities"]
edition.workspace = true
homepage.workspace = true
keywords = ["anytype", "raycast"]
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Edit Anytype documents in an external editor"

[dependencies]
anyhow.workspace = true
anytype.workspace = true
base16ct.workspace = true
clap.workspace = true
regex.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
sha2.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
# For keyboard input simulation
enigo = "0.6.1"
# For clipboard access
arboard = "3.6"
