//!
//! Downloads protobuf definitions from Anytype Heart and generates Rust sources in `src/gen`.
//!
//! Run the owning crate's recipe with a branch, tag, revision, or unprefixed release version:
//!
//! ```sh
//! just gen-protos ref=0.50.10
//! ```
//!

use std::fs;
use std::path::{Path, PathBuf};
use tonic_prost_build::configure;

const PROST_HEADER: &str = "// This file is @generated by prost-build.\n";
const USAGE: &str = "usage: gen-protos <path-to-anytype-heart-root> <anytype-heart-ref> <generated-date-utc>\n\
    (expects pkg/lib/pb/model/protos and pb/protos in that root)";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = std::env::args().skip(1);
    let source_root = args.next().ok_or(USAGE)?;
    let heart_ref = args.next().ok_or(USAGE)?;
    let generated_date = args.next().ok_or(USAGE)?;
    if args.next().is_some() {
        return Err(USAGE.into());
    }
    validate_heart_ref(&heart_ref)?;
    validate_generated_date(&generated_date)?;
    let source_root = PathBuf::from(source_root);

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .ok_or("unable to resolve repo root")?
        .to_path_buf();

    let out_dir = repo_root.join("src/gen");
    fs::create_dir_all(&out_dir)?;

    let tmp_dir = std::env::temp_dir().join(format!("anytype-rpc-protos-{}", std::process::id()));
    if tmp_dir.exists() {
        fs::remove_dir_all(&tmp_dir)?;
    }
    fs::create_dir_all(&tmp_dir)?;

    let model_dir = tmp_dir.join("pkg/lib/pb/model/protos");
    fs::create_dir_all(&model_dir)?;

    // Pre-process: Fix naming conflicts in models.proto
    let models_proto =
        fs::read_to_string(source_root.join("pkg/lib/pb/model/protos/models.proto"))?;
    let models_proto = models_proto
        // In Block message: rename `oneof content` to `oneof content_value`
        .replace("oneof content {", "oneof content_value {")
        // In Metadata message: rename `oneof payload` to `oneof payload_value`
        .replace(
            "oneof payload {\n        Payload.IdentityPayload",
            "oneof payload_value {\n        Payload.IdentityPayload",
        );
    fs::write(model_dir.join("models.proto"), models_proto)?;

    fs::copy(
        source_root.join("pkg/lib/pb/model/protos/localstore.proto"),
        model_dir.join("localstore.proto"),
    )?;

    // Stage 1: Compile model protos
    configure()
        .build_client(false)
        .build_server(false)
        .out_dir(&out_dir)
        .compile_protos(
            &[
                model_dir.join("models.proto").to_str().unwrap(),
                model_dir.join("localstore.proto").to_str().unwrap(),
            ],
            &[tmp_dir.to_str().unwrap()],
        )?;

    // Stage 2: Compile storage protos
    configure()
        .build_client(false)
        .build_server(false)
        .out_dir(&out_dir)
        .compile_protos(
            &[source_root
                .join("pkg/lib/pb/storage/protos/file.proto")
                .to_str()
                .unwrap()],
            &[
                source_root.to_str().unwrap(),
                source_root.join("pb").to_str().unwrap(),
            ],
        )?;

    // Stage 3: Compile service protos, referencing model types generated above
    configure()
        .build_client(true)
        .build_server(false)
        .out_dir(&out_dir)
        .extern_path(".anytype.model", "crate::model")
        .compile_protos(
            &[
                source_root
                    .join("pb/protos/service/service.proto")
                    .to_str()
                    .unwrap(),
                source_root
                    .join("pb/protos/commands.proto")
                    .to_str()
                    .unwrap(),
                source_root.join("pb/protos/events.proto").to_str().unwrap(),
                source_root
                    .join("pb/protos/snapshot.proto")
                    .to_str()
                    .unwrap(),
                source_root
                    .join("pb/protos/changes.proto")
                    .to_str()
                    .unwrap(),
            ],
            &[
                source_root.to_str().unwrap(),
                source_root.join("pb").to_str().unwrap(),
            ],
        )?;

    postprocess_generated_files(&out_dir, &heart_ref, &generated_date)?;
    fs::remove_dir_all(&tmp_dir)?;
    Ok(())
}

fn validate_heart_ref(heart_ref: &str) -> Result<(), &'static str> {
    if heart_ref.is_empty()
        || heart_ref
            .chars()
            .any(|character| character.is_whitespace() || character.is_control())
    {
        return Err("anytype-heart ref must be non-empty and contain no whitespace or controls");
    }
    Ok(())
}

fn validate_generated_date(generated_date: &str) -> Result<(), &'static str> {
    match generated_date.as_bytes() {
        [y1, y2, y3, y4, b'-', m1, m2, b'-', d1, d2]
            if [y1, y2, y3, y4, m1, m2, d1, d2]
                .into_iter()
                .all(u8::is_ascii_digit) =>
        {
            Ok(())
        }
        _ => Err("generated UTC date must use YYYY-MM-DD"),
    }
}

/// Adds generation provenance and adjusts doc lists that Clippy treats as malformed.
fn postprocess_generated_files(
    out_dir: &Path,
    heart_ref: &str,
    generated_date: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(out_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
            continue;
        }
        let text = fs::read_to_string(&path)?;
        let stamped =
            stamp_generated_source(&text, heart_ref, generated_date).ok_or_else(|| {
                std::io::Error::other(format!(
                    "generated source lacks the prost header: {}",
                    path.display()
                ))
            })?;
        let mut out = String::with_capacity(stamped.len());
        for line in stamped.lines() {
            if let Some(new_line) = indent_doc_list_line(line) {
                out.push_str(&new_line);
            } else if let Some(new_line) = indent_doc_list_continuation(line) {
                out.push_str(&new_line);
            } else {
                out.push_str(line);
            }
            out.push('\n');
        }
        fs::write(&path, out)?;
    }
    Ok(())
}

fn stamp_generated_source(text: &str, heart_ref: &str, generated_date: &str) -> Option<String> {
    let body = text.strip_prefix(PROST_HEADER)?;
    Some(format!(
        "{PROST_HEADER}// Generated on {generated_date} UTC from anytype-heart ref {heart_ref}.\n{body}"
    ))
}

fn indent_doc_list_line(line: &str) -> Option<String> {
    let trimmed = line.trim_start();
    if !trimmed.starts_with("/// ") {
        return None;
    }
    let prefix_len = line.len() - trimmed.len();
    let content = &trimmed[4..];
    if content.starts_with(' ') {
        return None;
    }
    let mut chars = content.chars();
    let mut digit_count = 0;
    let mut has_letter = false;
    while let Some(c) = chars.next() {
        if c.is_ascii_digit() {
            digit_count += 1;
            continue;
        }
        if digit_count == 0 {
            return None;
        }
        if c.is_ascii_alphabetic() {
            has_letter = true;
            let next = chars.next()?;
            if next != '.' {
                return None;
            }
        } else if c != '.' {
            return None;
        }
        break;
    }
    let indent = " ".repeat(prefix_len);
    let list_indent = if has_letter { "       " } else { "    " };
    Some(format!("{indent}///{list_indent}{content}"))
}

fn indent_doc_list_continuation(line: &str) -> Option<String> {
    let trimmed = line.trim_start();
    if !trimmed.starts_with("///    ") {
        return None;
    }
    let content = &trimmed[7..];
    if content.starts_with(' ') {
        return None;
    }
    let prefix_len = line.len() - trimmed.len();
    let indent = " ".repeat(prefix_len);
    Some(format!("{indent}///       {content}"))
}

#[cfg(test)]
mod tests {
    use super::{
        PROST_HEADER, stamp_generated_source, validate_generated_date, validate_heart_ref,
    };

    #[test]
    fn generated_source_records_date_and_ref() -> Result<(), Box<dyn std::error::Error>> {
        let source = format!("{PROST_HEADER}pub struct Example;\n");
        let stamped = stamp_generated_source(&source, "0.50.10", "2026-08-17")
            .ok_or("prost header should be recognized")?;

        assert_eq!(
            stamped,
            "// This file is @generated by prost-build.\n\
             // Generated on 2026-08-17 UTC from anytype-heart ref 0.50.10.\n\
             pub struct Example;\n"
        );
        Ok(())
    }

    #[test]
    fn generated_source_requires_the_prost_header() {
        assert!(stamp_generated_source("pub struct Example;\n", "develop", "2026-08-17").is_none());
    }

    #[test]
    fn heart_ref_rejects_empty_or_multiline_values() {
        assert!(validate_heart_ref("").is_err());
        assert!(validate_heart_ref("release\nspoofed").is_err());
        assert!(validate_heart_ref("release\0spoofed").is_err());
        assert!(validate_heart_ref("0.50.10").is_ok());
    }

    #[test]
    fn generated_date_requires_the_utc_recipe_format() {
        assert!(validate_generated_date("2026-08-17").is_ok());
        assert!(validate_generated_date("2026-8-17").is_err());
        assert!(validate_generated_date("2026-08-17 UTC").is_err());
    }
}
