# anytype
#
# SPDX-FileCopyrightText: 2025-2026 Steve Schoettler
# SPDX-License-Identifier: Apache-2.0

[package]
name = "anytype"
version.workspace = true
authors.workspace = true
categories = ["api-bindings"]
edition.workspace = true
homepage.workspace = true
keywords = ["anytype", "api", "client"]
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "An ergonomic Anytype API client in rust"

[features]
default = []

[lib]
path = "src/lib.rs"

[dependencies]
anytype-rpc.workspace = true
bytes.workspace = true
chrono.workspace = true
db-keystore.workspace = true
fs2.workspace = true
futures.workspace = true
getrandom.workspace = true
httpdate.workspace = true
keyring-core.workspace = true
libc.workspace = true
mime.workspace = true
parking_lot.workspace = true
prost.workspace = true
prost-types.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
sha2.workspace = true
snafu.workspace = true
strum.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tracing.workspace = true
zeroize.workspace = true

# these only needed if we don't directly import keyring
[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store = { version = "1.0.1", features = ["keychain", "protected"] }
[target.'cfg(target_os = "linux")'.dependencies]
linux-keyutils-keyring-store = { version = "1.0.0" }
[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
dbus-secret-service-keyring-store = { version = "1.0.0", features = ["crypto-rust", "vendored"] }
zbus-secret-service-keyring-store = { version = "1.0.0", features = ["rt-async-io-crypto-rust"] }
[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = "1.1.0"

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
png = "0.18"
serial_test = "3.5.0"
test-log.workspace = true
tokio = { workspace = true, features = ["test-util"] }
tracing-subscriber.workspace = true
url.workspace = true
