# dprint's html formatter doesn't like templates, which aren't valid html
excludes = ["site/themes/easydocs/templates/*.html"]
on-unmatched = "debug"

[formatter.biome]
command = "biome"
includes = [
  "*.css",
  "*.graphql",
  "*.gql",
  "*.js",
  "*.mjs",
  "*.cjs",
  "*.jsx",
  "*.ts",
  "*.mts",
  "*.cts",
  "*.tsx",
  "*.vue",
]
options = ["format", "--write", "--config-path=@GATE_BIOME_CONFIG@"]

[formatter.dprint]
command = "dprint"
includes = [
  "*.json",
  "*.jsonc",
  "*.json5",
  "*.md",
  "*.markdown",
  "*.toml",
  "*.yaml",
  "*.yml",
  "*.kdl",
  "*.html",
  "*.htm",
]
options = ["fmt", "--config", "@GATE_DPRINT_CONFIG@", "--config-discovery=ignore-descendants"]

[formatter.just]
command = "just"
includes = ["justfile", ".justfile", "*.just"]
options = ["--unstable", "--fmt", "-f"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.ruff]
command = "ruff"
includes = ["*.py", "*.pyi"]
options = ["format", "--config", "@GATE_RUFF_CONFIG@"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]
options = ["--edition", "2024"]
