# anytype-rpc
#
# SPDX-FileCopyrightText: 2025-2026 Steve Schoettler
# SPDX-License-Identifier: Apache-2.0
#
[package]
name = "anytype-rpc"
version.workspace = true
authors.workspace = true
categories = ["api-bindings"]
edition.workspace = true
homepage.workspace = true
keywords = ["anytype", "client", "grpc", "api"]
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
description = "Anytype gRPC client"

[dependencies]
chrono.workspace = true
http-body.workspace = true
prost-types.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true

# grpc
prost.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[dev-dependencies]
clap.workspace = true
serde_yaml_ng = "0.10.0"
tokio = { workspace = true, features = ["test-util"] }
