
_default:
    just --list

check:
    cargo build
    cargo clippy -- -D warnings
    fd -e rs | xargs rustfmt --edition 2024 --check

check-all: (check)
    cargo shear
    just spellcheck
    cargo audit -f ../Cargo.lock
    cargo outdated

# check for typos
spellcheck:
    typos
    cspell "**/*.{rs,md}"

