[package]
name = "gen-protos"
version = "0.1.2"
publish = false
edition = "2024"
authors = ["Steve Schoettler <stevelr-git@pm.me>"]
homepage = "https://github.com/stevelr/anytype"
license = "Apache-2.0"
repository = "https://github.com/stevelr/anytype"

[dependencies]
tonic-prost-build = "0.14.6"

[workspace]
